apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    repoURL: https://github.com/0penshifty/demo-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - demo-app.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

